#!/usr/bin/env python

top = '.'
out = "build"

def configure(conf):
    conf.load('tex')

    if not conf.env.PDFLATEX:
        conf.fatal("Could not find pdflatex")

def build(ctx):
    ctx(
            features = 'tex',
            type     = 'pdflatex', # pdflatex or xelatex
            source   = 'talk.tex', # mandatory, the source
            outs     = 'pdf', # 'pdf' or 'ps pdf'
            deps     = 'style.sty', # dependence
            prompt   = 1 # 0 for the batch mode
        )

    ctx.add_post_fun(post)  # copy PDF

    # add manual dependency such that the presentation is rebuilt if the style
    # package style.sty changes:
    #ctx.add_manual_dependency(ctx.path.find_node('talk.tex'), ctx.path.find_node('style.sty'))

def post(ctx):
    print("Copy PDF file to top directory")
    ctx.exec_command("cp {0}/talk.pdf".format(out) + " {0}".format(top))
    if ctx.options.view:
        print("Open PDF file in default PDF viewer")
        ctx.exec_command("xdg-open {0}/talk.pdf".format(out))

def options(ctx):
        ctx.add_option("--view", action="store_true", default=False,
                       help='view the PDf after it is built')
