#!/usr/bin/env python

top = '.'
out = "build"

def configure(conf):
    conf.load('tex')

    if not conf.env.PDFLATEX:
        conf.fatal("Could not find pdflatex")

def build(bld):
    bld(
            features = 'tex',
            type     = 'pdflatex', # pdflatex or xelatex
            source   = 'EDyn-PDE.tex', # mandatory, the source
            outs     = 'pdf', # 'pdf' or 'ps pdf'
            prompt   = 0 # 0 for the batch mode
        )
